CREATE SEQUENCE setor_seq START WITH 1;
CREATE TABLE SETOR(
    ID_SETOR NUMBER NOT NULL,
    NM_SETOR VARCHAR2(265) NOT NULL,
	PRIMARY KEY(ID_SETOR)
);

CREATE SEQUENCE usuario_seq START WITH 1;
CREATE TABLE USUARIO(
    ID_USUARIO NUMBER NOT NULL PRIMARY KEY,
    CD_MATRICULA VARCHAR2(10) NOT NULL UNIQUE,
    NM_USUARIO VARCHAR2(265) NOT NULL,
    CPF_USUARIO VARCHAR2(15) UNIQUE,
    DT_NASCIMENTO DATE NOT NULL,
    EMAIL_USUARIO VARCHAR2(64) NOT NULL,
    CEL_USUARIO VARCHAR2(15) NULL,
    ENDERECO_USUARIO VARCHAR2(265) NOT NULL, 
    ID_SETOR NUMBER NOT NULL,
    PSW_USUARIO VARCHAR2(265) NOT NULL,
    CONSTRAINT FK_USUARIO_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR) ON DELETE CASCADE
);

CREATE SEQUENCE covid_seq START WITH 1;
CREATE TABLE COVID(
    ID NUMBER NOT NULL PRIMARY KEY,
    DS_ARQUIVO VARCHAR2(256) NOT NULL ,
    DT_CRIACAO DATE NULL,	
    DT_ATUALIZACAO DATE NULL,
    ID_USUARIO NUMBER NOT NULL,
    SITE VARCHAR2(256) NOT NULL,
    DIRETORIO VARCHAR2(256) NOT NULL,
    CONSTRAINT FK_COVID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

insert into setor (id_setor, nm_setor) values (setor_seq.nextval, 'Tecnologia da Informação');
Insert into usuario (ID_USUARIO,CD_MATRICULA,NM_USUARIO,CPF_USUARIO,DT_NASCIMENTO,EMAIL_USUARIO,CEL_USUARIO,ENDERECO_USUARIO,ID_SETOR,PSW_USUARIO) values (usuario_seq.nextval,'1314','Administrador do sistema','12346578977',to_date('10/10/01','DD/MM/YYYY'),'email@email.com','11233445566','Rua A','1','25d55ad283aa400af464c76d713c07ad');
-- SENHA CADASTRADA 1 a 8